# Generated by Django 5.0.4 on 2024-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('skill', models.CharField(max_length=10)),
                ('fees', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
